# Generated by Django 4.2.26 on 2026-08-27 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('budget_preference', models.PositiveIntegerField(default=0)),
                ('preferred_transport', models.CharField(choices=[('walking', 'Walking'), ('public_transport', 'Public transport'), ('driving', 'Driving'), ('cycling', 'Cycling')], default='walking', max_length=30)),
                ('available_time_minutes', models.PositiveIntegerField(default=120)),
                ('travel_companions', models.CharField(choices=[('solo', 'Solo'), ('partner', 'Partner'), ('friends', 'Friends'), ('family', 'Family')], default='solo', max_length=20)),
                ('dietary_preferences', models.CharField(blank=True, max_length=120)),
                ('mobility_preferences', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
